version: '3.9'

services:
    frontend:
      image: cycloud-frontend
      container_name: cycloud-app
      build: .
      ports:
        - 3000:3000
      environment:
        - NODE_ENV=development
        - CHOKIDAR_USEPOLLING=true
      volumes:
        - .:/app/
        - /app/node_modules
      stdin_open: true
      restart: on-failure